name: deploy gh-pages
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build and deploy gh-pages
    env:
      GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      USER_NAME: Limoer96
      USER_EMAIL: myt19960503@outlook.com
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: enable corepack
        run: |
          corepack enable
      - name: install
        run: |
          yarn
      - name: docs build
        run: |
          yarn docs:build
      - name: run sync
        run: |
          git init
          git config --local user.name $USER_NAME
          git config --local user.email $USER_EMAIL
          node ./scripts/gh-pages.js
